
// mutation($name: String!, $containerNode: SemanticLayoutNodeWhereUniqueInput, $children: [SceneCreateWithoutParentInput!]) {
    //     createScene (data: {
        //       name: $name,
        //       containerNode: { connect: $containerNode}
        //       children: { create: $children}
        //     }) { id }
        //   }

// TODO: Turn this into a generator of some sort

// {
//     "name": "autoGeneratedSceneOne",
//     "containerNode": { "id": "cjkssfz4bw32g0b77a1oz5n2x"},
//     "children": [{
//         "name": "autoGeneratedSceneOneChildOne",
//       	"children": { "create": [{ ... }] },
//         "containerNode": {
//           "create": {
//             "position": { "create": {
//               "x": 0,
//               "y": 0,
//               "z": 0
//             	}
//             },
//             "rotation": { "create": {
//               "x": 0,
//               "y": 0,
//               "z": 0 
//             }
//             },
//             "scale": { "create": {
//               "x": 0,
//               "y": 0,
//               "z": 0
//             }
//         },
//         "physicalModel": { "create": {
//             "name": "autoGeneratedSceneOneChildOnePhysicalModel",
//             "physicalAsset": { "create": {
//                 "name": "autoGeneratedSceneOneChildOnePhysicalAsset",
// 								"modelType": "OBJ",
//                 "objPath": "path/to/obj"
//             }}
//         }}
//           }
//         },
//       "semanticLayoutNodes": { "create": [{
//         "name": "autoGeneratedSceneOneChildOneSemanticLayoutNodeOne",
//         "position": { "create": {
//               "x": 0,
//               "y": 0,
//               "z": 0
//             	}
//             },
//             "rotation": { "create": {
//               "x": 0,
//               "y": 0,
//               "z": 0 
//             }
//             },
//             "scale": { "create": {
//               "x": 0,
//               "y": 0,
//               "z": 0
//             }
//             },
//         "physicalModel": { "create": {
//           "name": "autoGeneratedSceneOneChildOneSemanticLayoutNodePhysicalModel",
//           "physicalAsset": { "create": {
//             "name": "autoGeneratedSceneOneChildOneSemanticLayoutNodePhysicalAsset",
//             "modelType": "OBJ",
//             "objPath": "path/to/obj"
//           } }
//         } }
//       }]}
//     }]
// }

